############################################################

# 0.1. Config

@PORT={{$dotenv NEXTJS_PORT}}
@LOCAL_ADDR=http://localhost:{{PORT}}
@API_URL={{LOCAL_ADDR}}/api

############################################################

# 0.2. Misc

### 0.2.1. Health

GET {{API_URL}}/health

### 0.2.2. Reset DB

POST {{API_URL}}/reset

############################################################

# 1. Pattern Search

@PATTERN_SEARCH=pattern-search

### 1.1. Sequential

@SEQUENTIAL_PATTERN=pdppddcp

GET {{API_URL}}/{{PATTERN_SEARCH}}/sequential/{{SEQUENTIAL_PATTERN}}

## 1.2. Stones

@BLACK_STONES_EQUALS=qcpcoc
@WHITE_STONES_EQUALS=odpdqd

### 1.2.1 Stones Contains

GET {{API_URL}}/{{PATTERN_SEARCH}}/stones/{{BLACK_STONES_EQUALS}}/{{WHITE_STONES_EQUALS}}

### 1.2.2 Stones Equals

GET {{API_URL}}/{{PATTERN_SEARCH}}/stones/{{BLACK_STONES_EQUALS}}/{{WHITE_STONES_EQUALS}}?equals=true

############################################################
