############################################################

# 0.1. Config

@PORT={{$dotenv NEXTJS_PORT}}
@LOCAL_ADDR=http://localhost:{{PORT}}
@API_URL={{LOCAL_ADDR}}/api

############################################################

# 0.2. Misc

### 0.2.1. Health

GET http://localhost:3000/api/health

### 0.2.2. Reset DB

POST {{API_URL}}/reset

############################################################
